- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: 'setup.py'
    arguments: 'bdist_wheel --universal'