# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python38:
      python.version: '3.8'

variables:
  baseFolder: $(Build.SourcesDirectory)/Code/HandwritingSmoother
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    dir $(baseFolder)
    python -m pip install --upgrade pip
    pip install -r $(baseFolder)/requirements.txt
  displayName: 'Install dependencies'

- script: |
    python $(baseFolder)/setup.py sdist
  displayName: 'Artifact creation'

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: 'smucapstone'

- task: CopyFiles@1
  inputs:
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'pywritesmooth'
    publishLocation: 'Container'