from AutoEncoderTrainer import AutoEncoderTrainer
from GANTrainer import GANTrainer
from RNNTrainer import RNNTrainer
from StyleTransferTrainer import StyleTransferTrainer
from SVDTrainer import SVDTrainer
from TrainerInterface import TrainerInterface